### PR TITLE
Social logins

### LINKED ISSUE #43: improve login/register form
Improve the login/register for better user experience

- submit on enter
- maybe not vuelidate on hover over button
- show disabled state to user in different opacity
- hover effect on button
- error messages (username alr taken, password/email wrong, ...)

### PR DESCRIPTION
**Pull request by Mathematti**

### CODE REVIEW

File: src/views/RegistrationView.vue [hunk 1]
```diff
@@ -122,7 +195,7 @@ export default {
         <FliegerIllustration class="h-[85vh] ml-[1%]"/>
       </div>
     </div>
-    <div class="xl:w-1/2 md:w-2/3 sm:w-[100%] items-center justify-center flex ">
+    <div class="xl:w-1/2 md:w-2/3 sm:w-[100%] items-center justify-center flex ml-5 -mr-0.5">
       <Footer class="bottom-0 w-full md:fixed"/>
```
Comment (EinSev) [inline src/views/RegistrationView.vue]: Remove md:fixed so it doesn't look like that if bookmark bar is displayed in the browser.

image

File: src/components/illustrations/MicrosoftLoginIllustration.vue [hunk 2]
```diff
@@ -0,0 +1,67 @@
+<template>
+  <svg height="41" viewBox="0 0 215 41" width="215" xmlns="http://www.w3.org/2000/svg"><title>MS-SymbolLockup</title>
```
Comment (EinSev) [inline src/components/illustrations/MicrosoftLoginIllustration.vue]: Can you change the title here to maybe nothing. Thats the text that is being displayed when hovering over the "button"

File: src/views/LoginView.vue [hunk 3]
```diff
@@ -1,83 +1,145 @@
...
+      {
+        email: state.contact.email,
+        password: state.password
       }
+  )
+  if (error) {
+    toast.add({
+      severity: 'error',
+      summary: 'Fehler beim einloggen',
+      detail: 'Du hast einen Falschen Benutzernamen oder ein falsches Passwort angegben.',
```
Comment (EinSev) [inline src/views/LoginView.vue]: Please change to "Du hast eine falsche E-Mail oder ein falsches Passwort angegeben"

File: src/views/RegistrationView.vue [hunk 4]
```diff
@@ -82,37 +131,61 @@ export default {
...
+                     data-logo_alignment="left"
+                     data-shape="pill"
+                     data-size="large"
+                     data-text="signin_with"
+                     data-theme="outline"
+                     data-type="standard">
+                </div>
+              </div>
+              <div class="mb-4">
+                <MicrosoftLoginIllustration @click="handleSignInWithMicrosoft()"/>
```
Comment (EinSev) [inline src/views/RegistrationView.vue]: change cursor to something like cursor-pointer

[Tailwind Docs](https://tailwindcss.com/docs/cursor)

File: src/views/RegistrationView.vue [hunk 5]
```diff
@@ -82,37 +131,61 @@ export default {
...
+              <input v-model=v$.passwordRepeat.$model
                      class="font-nunito text-xl border rounded border-none focus:outline-none focus:ring-2 focus:ring-call-to-action pl-1"
-                     placeholder="Passwort eingeben">
+                     placeholder="Passwort eingeben"
+                     type="password" @keyup.enter="signUp">
               <p v-if="v$.passwordRepeat.$error" class="text-delete text-base font-nunito">Nicht ident zu Passwort</p>
               <div class="check">
                 <label class="font-nunito text-base">
-                  <input type="checkbox" class="p-3" v-model="v$.accepted.$model">
+                  <input v-model="v$.accepted.$model" class="p-3" type="checkbox">
```
Comment (EinSev) [inline src/views/RegistrationView.vue]: If possible make checkbox a bit bigger (I know it has nothing directly to do with your PR)

File: src/views/LoginView.vue [hunk 6]
```diff
@@ -102,24 +164,42 @@ export default {
...
+                     data-logo_alignment="left"
+                     data-shape="pill"
+                     data-size="large"
+                     data-text="signin_with"
+                     data-theme="outline"
+                     data-type="standard">
+                </div>
+              </div>
+              <div class="mb-4">
+                <MicrosoftLoginIllustration @click="handleSignInWithMicrosoft()"/>
```
Comment (EinSev) [inline src/views/LoginView.vue]: change cursor to something like cursor-pointer

[Tailwind Docs](https://tailwindcss.com/docs/cursor)

**Review by EinSev — APPROVED** [review]
