### PR TITLE
fix: fixed a bug and added a feature to calendar

### LINKED ISSUE #91: initialize calendar with journey from date
initialize calendar with journey from date so you can drag activities right away and dont have to find the start week of your journey

### PR DESCRIPTION
**Pull request by Ixpiria**

### CODE REVIEW

File: src/components/Calender.vue [hunk 1]
```diff
@@ -21,6 +21,7 @@ export default {
   data() {
     return {
       currentUserRole: ref(),
+      noEvents: ref("true"),
```
Comment (Mathematti) [inline src/components/Calender.vue]: why assign this as a string here?

File: src/components/Calender.vue [hunk 2]
```diff
@@ -35,11 +36,13 @@ export default {
       kosten: ref(""),
       beschreibung: ref(""),
       ausgewaeltesEvent: ref(""),
```
Comment (Mathematti) [inline src/components/Calender.vue]: typo: ausgewaehltesEvent

File: src/components/JourneyCalendar.vue [hunk 3]
```diff
@@ -298,12 +325,12 @@ export default {
...
                 <RouterLink :to='$route.fullPath + "/aktivitaet/neu"' class="col-start-6 bg-call-to-action
-                rounded-3xl flex text-text-black font-nunito text-center items-center justify-center text-xl font-bold shadow-md hover:opacity-80">
-                  <AddActivityIllustration class="m-2 w-[20%]"/>
+                rounded-3xl flex text-text-black font-nunito text-center items-center justify-center text-xl font-bold">
+                  <AddActivityIllustration class="m-2 w-[20%]"></AddActivityIllustration>
                   Erstellen
                 </RouterLink>
               </div>
-              <div id="planned-tasks" class="flex bg-background p-1 planned-tasks min-w-32 rounded-md">
+              <div id="planned-tasks" class="flex flex-wrap bg-background p-1 planned-tasks text-center justify-center">
```
Comment (Mathematti) [inline src/components/JourneyCalendar.vue]: should only be centered if there are no activities, otherwise it looks horrible
grafik

File: src/components/Calender.vue (hunk 2 above)
Comment (Mathematti) [reply src/components/Calender.vue]: Still relevant even though outdated

File: src/components/Calender.vue (hunk 1 above)
Comment (Mathematti) [reply src/components/Calender.vue]: Still relevant even though outdated

File: src/components/JourneyCalendar.vue [hunk 4]
```diff
@@ -54,7 +57,6 @@ export default {
     };
   },
   async mounted() {
-    await this.initializeData();
     this.setupDraggable();
   },
   methods: {
```
Comment (Mathematti) [inline src/components/JourneyCalendar.vue:64]: Use route directly below this is unused I believe

File: src/components/JourneyCalendar.vue [hunk 5]
```diff
@@ -172,6 +196,8 @@ export default {
             }
 
             this.index++;
+          } else {
+            this.noEvents = false;
```
Comment (Mathematti) [inline src/components/JourneyCalendar.vue:201]: This used to be a ref and now it's just false?

Comment (Ixpiria) [reply src/components/JourneyCalendar.vue:201]: this is necessary like this since adding the .value will result in an error

**Review by Mathematti — APPROVED** [review]

**Comment by Mathematti** [comment]
do not merge yet, this is broken

**Review by Mathematti — APPROVED** [review]
